In [14]:
#from https://stackoverflow.com/questions/54300263/connect-to-aws-rds-postgres-database-with-python
import psycopg2


from sqlalchemy import create_engine

engine = create_engine('postgresql+psycopg2://database:Password@host:port/postgres')

In [15]:
import pandas as pd

df = pd.read_csv('Data_Extraction_Transform/dropped_cols_month_earthquake.csv', index_col=0)
df.head(5)

,id,tsunami,felt,time,latitude,longitude,depth,mag,magType,gap,net,updated,place,type,locationSource
0,nn00818986,0,NaN,2021-08-19T02:53:29.951Z,38.541200,-119.463900,3.60,1.30,ml,58.29,nn,2021-08-19T02:56:56.695Z,"3 km NNE of Walker, California",earthquake,nn
1,ci40014776,0,NaN,2021-08-19T02:49:35.880Z,35.896667,-117.729167,4.48,0.72,ml,72.00,ci,2021-08-19T02:53:05.273Z,"17km ESE of Little Lake, CA",earthquake,ci
2,ak021am2mkg5,0,NaN,2021-08-19T02:49:14.046Z,59.865100,-153.176400,102.60,1.60,ml,NaN,ak,2021-08-19T03:02:14.791Z,"52 km E of Pedro Bay, Alaska",earthquake,ak
3,nc73611791,0,NaN,2021-08-19T02:46:16.400Z,38.784668,-122.751000,0.33,1.03,md,84.00,nc,2021-08-19T02:47:54.191Z,"1km NNE of The Geysers, CA",earthquake,nc
4,ak021am2l4yc,0,NaN,2021-08-19T02:42:46.880Z,56.657400,-157.265100,0.50,2.90,ml,NaN,ak,2021-08-19T02:50:26.938Z,"80 km ENE of Chignik, Alaska",earthquake,ak

In [16]:
df.to_sql('earthquake_cleaned', engine, if_exists='replace', index = False)

In [18]:
engine.dispose()